### ISSUE TITLE
Complete Crash due to NanoJ-Core

### ISSUE THREAD

**Issue by JonathanCSmith** [guijacquemet/Fast4DReg#2]
I am currently unable to run this due to crashing (seems to be related to: https://github.com/HenriquesLab/NanoJ-Core/issues/3) is there a known work around for this?

**Comment by guijacquemet** [comment]
Hi,
Thanks for reaching out!

The most common issue related to NanoJ is due to OpenCL not being installed or misbehaving. We are working on a new version of Fast4DReg that does not require OpenCL. 

You can, however, try the following:

Fiji crashing without notice:

Windows might not have OpenCL installed. If you experience Fiji crashing without notice, [install the OpenCL through the Microsoft store library.](https://www.microsoft.com/en-us/p/opencl-and-opengl-compatibility-pack/9nqpsl29bfff?activetab=pivot:overviewtab)

**Comment by JonathanCSmith** [comment]
Thanks, I switched to OS X vs Windows and this worked great! Excellent plugin!

**Comment by HannahSHeil** [comment]
There is also a description of a fix for Windows users [here](https://github.com/HenriquesLab/NanoJ-eSRRF/wiki#nanoj-esrrf-opencl-issues).
