### ISSUE TITLE
Error: n frames in drift table != n frames in image

### ISSUE THREAD

**Issue by dpoburko** [guijacquemet/Fast4DReg#3]
Apologies for not posting this sooner. When trying to run fast4DReg, I get the error below in the bug report. This is my first Github issue submission, so I hope I have uploaded the image correctly with the error message. I have pasted the debug and log outputs below as well. There is a note in the log that NanoJ has detected a composite image. This is weird because the image has a single channel (stack dimensions: width =1408, height = 1040, channels = 1, slices = 1, frames = 10).

Bioformats is installed. 

NanoJCore is installed, and NanoJCore>Drift Correction>Estimate Drift (checking Apply Drift) seems to work fine.

![fast44DReg error img](https://user-images.githubusercontent.com/42272290/190860439-d62adb27-9724-4ef7-a4a1-6c80ee2ca245.jpg)

**_The debug output is pasted below._**
Name	*	Value
Memory	*	281MB of 14500MB (1%)
nImages()	*	8
getTitle()	*	"DUP"
extend_stack_to_fit (g)	*	1
time_z (g)	*	1
crop_output (g)	*	1
projection_type_xy (g)	*	"Max Intensity"
z_registration (g)	*	0
reference_z (g)	*	"first frame (default, better for fixed)"
max_z (g)	*	0
my_file_path (g)	*	"C:\tempImages\SBR010_HeLa\SBR010concatenated_ch1_B4_10.tif"
max_xy (g)	*	0
ram_conservative_mode (g)	*	0
projection_type_z (g)	*	"Max Intensity"
exp_nro (g)	*	1
time_xy (g)	*	1
XY_registration (g)	*	1
reslice_mode (g)	*	"Top"
reference_xy (g)	*	"previous frame (better for live)"
MonthNames	*	array[12]
year	*	"2022"
month	*	8
week	*	6
day	*	17
hour	*	6
min	*	47
sec	*	5
msec	*	476
timeStamp	*	"2022-Sep-17-001"
filename_no_extension	*	"SBR010concatenated_ch1_B4_10"
results	*	"C:/tempImages/SBR010_HeLa/SBR010concatenated_ch1_B4_10_2022-Sep-17-001\"
settings_file_path	*	"C:/tempImages/SBR010_HeLa/SBR010concatenated_ch1_B4_10_2022-Sep-17-001\SBR010con..."
DriftTable_path_XY	*	"C:/tempImages/SBR010_HeLa/SBR010concatenated_ch1_B4_10_2022-Sep-17-001\SBR010con..."
DriftTable_path_Z	*	"C:/tempImages/SBR010_HeLa/SBR010concatenated_ch1_B4_10_2022-Sep-17-001\SBR010con..."
t_start	*	1663422425490.0000
options	*	"open=[C:\tempImages\SBR010_HeLa\SBR010concatenated_ch1_B4_10.tif] autoscale colo..."
width	*	1408
height	*	1040
channels	*	10
slices	*	1
frames	*	1
thisTitle	*	"SBR010concatenated_ch1_B4_10.tif"
i	*	0

Error:		Number of frames in drift-table different from number of frames in image... in line 200:
	
		run ( "Correct Drift" , "choose=[" + DriftTable_path_XY + "DriftTable.njt]" <)> ; 

**_Log Output:_**

My file path: C:\tempImages\SBR010_HeLa\SBR010concatenated_ch1_B4_10.tif
Estimating the xy-drift....
xy-drift table path: C:/tempImages/SBR010_HeLa/SBR010concatenated_ch1_B4_10_2022-Sep-17-001\SBR010concatenated_ch1_B4_10-Max Intensity_xy_

Applying the xy-correction to the stack....
WARNING: detected composite image. NanoJ is optimized for pure image stacks and may yield errors.
ERROR: java.lang.RuntimeException: Macro canceled
in DialogListener of nanoj.core.java.gui._BaseDialog_$MyDialogListener@198676c5
at ij.macro.Interpreter.error(Interpreter.java:1404)
from ij.macro.Interpreter.abort(Interpreter.java:2152)

**Comment by jpylvanainen** [comment]
Hi @dpoburko thanks for posting. Seems like you are using a 2D time-lapse image, not 3D. Fast4DReg does not yet support the correction of 2D images, only 3D. For 2D data, you should use the NanoJ as you described above.

Hope this helps! :)

**Comment by jpylvanainen** [comment]
Hi @dpoburko. I'm happy to let you know that today we have released a new version of Fast4DReg, that can also correct drift in 2D videos. This new version is now available as Fiji update site (requires Fiji update). Please give it a go if you can!

**Comment by caleb-smithereens19** [comment]
Hello, my apologies for reaching back out onto this thread; I just believe I am having the same issue and cannot figure out why this occurring. I'm currently trying to use this program to correct in drift of the images I have gotten using the diSPIM microscope I use within my lab. Our images are being shifted/drifting due to the camera fans yet at the moment we don't have the availability to introduce water cooling. My next best thought was to try and find something that could correct the shifting we are seeing.

The images I am inputting into the program are TIFs with approximately 80 frames. Just a small image set that I can use to show my PI that this can be used. Anyway, whenever I run the program under (time estimate+apply), it just keeps saying that the frames in the drift table do not match the frames of my image. I have made sure my image is a single channel. Each frame is a separate z-stack of the cell I've imaged however and not specifically a time point so I felt this could perhaps be the issue. The outputs of the program are created in a folder, however they are all quite empty. Any advice you could provide would be much appreciated! :)

If I need to provide more information, please don't hesitate to ask!
